### ISSUE TITLE
Is psycopg2 needed?

### ISSUE THREAD

**Issue by jhamrick** [suchow/Wallace#156]
It's in the requirements, but breaks if postgresql isn't installed (as it is python bindings for postgres). Postgres isn't required when installing wallace locally, which means that psycopg2 probably shouldn't be required, either.

**Comment by suchow** [comment]
Yes, it's needed — everything I've read has suggested that it's a bad idea to test using a different kind of database than you use in production. So it would be better for us to get psycopg2 installing cleanly than to make it optional.
