### ISSUE TITLE
requests arrive missing arguments

### ISSUE THREAD

**Issue by thomasmorgan** [suchow/Wallace#241]
Most Wallace routes require the `participant_id` to be specified. This is a unique identifier that allows Wallace to recognize who is making the request. However, on the most recent large scale experiment we got a moderate number of these errors:

```>>>> ????? Error: /node request, participant_id not specified```

This indicates that a request was received that did not include this necessary argument. I am not sure where such a request could have come from as the experiment front end **always** includes this value with every request.

I am not sure what this could be caused by, however, here are three further bits of information that may or may not be relevant:

1 - Sometimes /node GET requests appear in the logs:

```Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a heroku/router:  at=info method=GET path="/node" host=w4a1dd857-f550-4d26-aef6-4e7a.herokuapp.com request_id=30577328-04dd-4dca-8cc5-9d30b1f0178a fwd="199.19.249.196" dyno=web.2 connect=1ms service=13ms status=403 bytes=1457```

This is extremely unusual because although this route exists it is never called by any existing experiments. So perhaps the requests that are missing participant_ids come from the same place as the /node GET requests, wherever that might be.

2 - Around the same time as the missing argument error, there is also this error:

```
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:  2015-10-15 14:53:53 [14] [DEBUG] GET /inexp 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:  2015-10-15 14:53:53,538 GET /inexp 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:  2015-10-15 14:53:53,539 Exception on /inexp [GET] 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:  Traceback (most recent call last): 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      response = self.full_dispatch_request() 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      rv = self.handle_user_exception(e) 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      reraise(exc_type, exc_value, tb) 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      rv = self.dispatch_request() 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      return self.view_functions[rule.endpoint](**req.view_args) 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/src/psiturk/psiturk/experiment.py", line 666, in regularpage 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      return render_template(pagename) 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list), 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      return self.get_template(template_name_or_list, parent, globals) 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      return self._load_template(name, self.make_globals(globals)) 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      cache_key = self.loader.get_source(self, name)[1] 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:      raise TemplateNotFound(template) 
Oct 15 07:53:53 w4a1dd857-f550-4d26-aef6-4e7a app/web.8:  TemplateNotFound: inexp
```
This is something to do with psiturk that I do not understand, however, the correlation in time implies some sort of causal relationship between this error and the missing argument error (the psiturk error comes about 1s before the missing argument error).

3 - Even though the experiment is now over and the server has no dynos we are getting a steady stream of requests. I have no idea where most of these are coming from. For example:

```
Oct 21 09:03:20 w4a1dd857-f550-4d26-aef6-4e7a heroku/router: at=error code=H14 desc="No web processes running" method=GET path="/consent?hitId=34KYK9TV2R88SUI3SLTYEK9YDPRBSR&assignmentId=38SKSKU7R1XYY9ZD4PTGD5U3H7MIL3&workerId=AGP1IXSTAD126&mode=live" host=w4a1dd857-f550-4d26-aef6-4e7a.herokuapp.com request_id=45f5ca0f-ce34-40bc-8f39-f95f2ad3f5e8 fwd="157.55.39.147" dyno= connect= service= status=503 bytes=
```
Could these requests be coming from the same place as the requests with missing participant_ids?

**Comment by cewing** [comment]
@suchow, @thomasmorgan,

I've picked this up to start working on it.  It appears that I am blocked even from local testing by the lack of a PsiTurk api key.  I did submit a request yesterday and have yet to hear back from them about it.  Any idea how long it usually takes?  

Is there a way to run the software without having a psiturk key?

**Comment by suchow** [comment]
@cewing I just sent you an email.

**Comment by cewing** [comment]
In looking over the flask view code that is the `/node` endpoint, I'm seeing something that is not a good practice.  This is the code you have in place to cover the absence of 'participant_id' as an incoming data point:

```python
    try:
        participant_id = request.values["participant_id"]
        key = participant_id[0:5]
    except:
        msg = "/node request, participant_id not specified"
        exp.log("Error: {}".format(msg))
        data = {
            "status": "error",
            "html": error_page(error_type=msg)
        }
        return Response(dumps(data), status=403, mimetype='application/json')
```

The problem is line 4 in that block, where you use the `except` clause without specifying what type of error you are expecting to catch.  This means that you might not be catching the problem you think you are catching.  In general the line `participant_id = request.values['participant_id']` should be expected to raise a KeyError if there is no participant id, so it would be better to do this:

```python
try:
    participant_id = request.values['participant_id']
    ...
except KeyError:
   ...
```

That way you can be certain that the problem is coming from the lack of a participant_id and not from some api change in the request object that is causing a different error.

That being said, the fact that this error block returns a 403 response and the log files you are seeing for odd GET requests (which show a response status of 403) suggest that these are not just related, they are in fact the same request.  The unexpected GET requests you are seeing are most likely the very requests that are causing the missing participant_id errors.

**Comment by cewing** [comment]
Another item of note.  You have a number of spots in the `node` view that return an error response.  Each has a message associated with it, but all use the exact same HTTP error code (403).  That error code is generally used to mean "Forbidden" which should suggest that the user has requested a resource that they are not allowed to view.  For some of the conditions causing error responses (such as those where participant_id leads you to believe that the participant is requesting a node intended for a different client) this is a good code.  However, for some, a more appropriate error code might help you to disambiguate which of the various error conditions threw the error response you are seeing in your log.  

For example, the error response that is returned when there is no participant_id might be better cast as an HTTP 400 response, which indicates that the request received was bad (in this case, missing values that it needs).

**Comment by cewing** [comment]
A further comment:

when you use url request vars to pass information to the server, this is a brittle proposition.  The `node` endpoint responds to any request that has the form `/node`, regardless of whether that request is good or not.  It might be advisable to take required parameters like `participant_id` and `node_id` and put them into the URL like so:

```python
@custom_code.route("/node/<participant_id>/<node_id>", methods=["POST", "GET"])
def node(participant_id, node_id):
    # ...
```
If you use this pattern, then requests that do not have a participant_id will not match a URL and will be responded to as 404, which is really what you want anyway.  That will happen entirely outside the realm of your app, and you'll be able to rely on only requests with the required parameters making it as far as the view code.

**Comment by thomasmorgan** [comment]
@cewing thanks for all these points. I will implement all of these so we can test them as part of the next study.

**Comment by thomasmorgan** [comment]
ok, I have made the changes you suggested Cris and pushed them to master in 3 commits
