### ISSUE TITLE
Code smells in custom.py

### ISSUE THREAD

**Issue by suchow** [suchow/Wallace#248]
A. Some of our Flask routes return a JSON representation of one or more Wallace objects (e.g., a set of `transmission`s from one node to another). The Wallace object has many attributes (e.g. `transmission.id`) and we want as many of these as possible to be serialized as JSON in the response. Right now, the code for doing this is:

```
        data = []
        for t in transmissions:
            data.append({
                "id": transmission.id,
                "vector_id": transmission.vector_id,
                "origin_id": transmission.origin_id,
                "destination_id": transmission.destination_id,
                "info_id": transmission.info_id,
                "network_id": transmission.network_id,
                "creation_time": transmission.creation_time,
                "receive_time": transmission.receive_time,
                "status": transmission.status,
                "property1": transmission.property1,
                "property2": transmission.property2,
                "property3": transmission.property3,
                "property4": transmission.property4,
                "property5": transmission.property5
            })
```

It seems that it would be better to use something like `json.dumps(transmission.__dict__)`, but some of these properties are SQLAlchemy objects and so things are a little more complicated than that.

What's the best way to handle this?

**Comment by suchow** [comment]
2. Many of our models have `__init__` methods. This seems strange, but I remember it being necessary for something:

```
    def __init__(self, info_in, info_out=None):
        self.check_for_transformation(info_in, info_out)
        self.info_in = info_in
        self.info_out = info_out
        self.node = info_out.origin
        self.network = info_out.network
        self.info_in_id = info_in.id
        self.info_out_id = info_out.id
        self.node_id = info_out.origin_id
        self.network_id = info_out.network_id
```

@thomasmorgan, can you remind us why this way needed?

**Comment by suchow** [comment]
3. Some models are subclassed (?), with the child models having special kinds of data not necessarily shared by the parents. For example, `Networks` share many things, but specific kinds of networks may have their own properties --- e.g., a scale-free network has two parameters, `m` and `m0` that determine the size of the starting cluster and the number of new attachments made by a newcomer. We want all the Networks to be stored in the same table, so what we did was to create a set of generic properties `property1`, `property2`, etc. that each subclass uses as needed. This seems kind of ugly. It means that every model has:

```
    # unused by default, these columns store additional properties used
    # by other types of node
    property1 = Column(String(26), default=None)
    property2 = Column(String(26), default=None)
    property3 = Column(String(26), default=None)
    property4 = Column(String(26), default=None)
    property5 = Column(String(26), default=None)
```
It also means that there is a bunch of extra work needed to map a user-friendly name to the column:

```
    def __init__(self, m0, m):
        """Store m0 in property1 and m in property2."""
        self.property1 = repr(m0)
        self.property2 = repr(m)

    @property
    def m0(self):
        """Number of nodes in the fully-connected core."""
        return int(self.property1)

    @property
    def m(self):
        """Number of connections that a newcomer makes."""
        return int(self.property2)
```

Are we doing the right thing here?

**Comment by thomasmorgan** [comment]
@suchow a reply and some extra info:

**A**:
Perhaps we can give each object a method that returns the dictionary of just the desired properties. So:

in custom.py:
```
data = []
        for t in transmissions:
            data.append(t.custom_dict())
```
meanwhile in models:
```
class Transmission...
    def custom_dict(self):
        return {
                "id": self.id,
                "vector_id": self.vector_id,
                "origin_id": self.origin_id,
                "destination_id": self.destination_id,
                "info_id": self.info_id,
                "network_id": self.network_id,
                "creation_time": self.creation_time,
                "receive_time": self.receive_time,
                "status": self.status,
                "property1": self.property1,
                "property2": self.property2,
                "property3": self.property3,
                "property4": self.property4,
                "property5": self.property5
            }
```
Also, I just noticed a bug in the code you posted. It should either be `for transmission in transmissions` or `t.id` etc.

**B**:
It's because most objects are created by reference to other objects (so the transformation is created by passing and info_in and an info_out) and then it mines these objects for its other properties. For example the `node` of the transformation is extracted from its `info_out`. In an earlier version (that didn't use __init__) we just said that to get the node of a transformation, get its info_out and then get the info_out's node. However, this is slow because you end up doing extra queries to get a single value (sometimes really slow, for instance to get the network of a transformation would involve 4 queries: transformation -> info_out -> node -> network). The new method does these extra queries just once when the object is created and then stores the result in the object itself so in future these values can be looked up with a single query.

**C**:
Jordan's description of the problem is good. I would just note that it can get even messier, for instance, in `Agent` (in nodes.py):
```
    @hybrid_property
    def fitness(self):
        """Endow agents with a numerical fitness."""
        if self.property1 is None:
            return None
        else:
            return float(self.property1)

    @fitness.setter
    def fitness(self, fitness):
        """Assign fitness to property1."""
        self.property1 = repr(fitness)

    @fitness.expression
    def fitness(self):
        """Retrieve fitness via property1."""
        return cast(self.property1, Integer)
```
These three functions "convert" node.property1 into node.fitness allowing fitness to be gettable, settable,  and queryable. A bit clunky!

**Comment by alecpm** [comment]
**A:** I would say the explicit definition of your JSON serialization dictionary is good idiomatic python and much better than something like `json.dumps(transmission.__dict__)`, which could easily pull in data you're not interested in and is also dependent on specifics of the implementation of attribute storage on the transmission instances (which you can't really rely on with DB model instances, especially when they have custom properties/descriptors).

If you're repeating the same serialization code in a few places, then it probably makes sense to centralize this as a method/property of the model object as @thomasmorgan suggests.  This would also move the serialization code closer to where the data is defined, making it more likely that you'll keep things in sync over time as the data changes.

In the pyramid world, it's fairly standard to add a `__json__` method to models and other content objects. That method returns a python representation of the object (usually a dict) made up of JSON types.  There's no reason not to do the same for your models in Flask.  You can either call this method explicitly before passing the data to `json.dumps`, or you can define and use a custom JSONDecoder as demonstrated here:

http://stackoverflow.com/questions/24030284/method-to-serialize-custom-object-to-json-in-python

**B:** Regarding the `__init__` methods (constructors) in your models, it's quite standard to have those, at least for any objects which have required attributes.  It looks like you're doing a little bit of validation/transformation in those constructors, which isn't unusual either, but could be a source of problems if those methods aren't efficient or are error prone.  I'm not seeing anything obviously problematic there, though the check:

    (info_in not in [t.info for t in node.transmissions(direction="incoming", status="received")])

at https://github.com/suchow/Wallace/blob/master/wallace/models.py#L1213 looks like it could pose an issue if that query is likely to return a large number of objects.  It seems like performing that test at the DB query level would probably be better, unless the result set is guaranteed to be small.

**C:** This is a bit unusual and, as you indicate, results in some complexity in the sub-classes. However, if the goal is to store a limited number of attributes in a single central table, while providing a clean non-generic API at the python level to access those generic attributes, then this seems like a reasonable way to go about doing that.  My one critique is that if you expect that `fitness` will have a value more often than not, then it would be a tiny bit more efficient and "pythonic" to use a `try/except` block, e.g.:

    @hybrid_property
    def fitness(self):
        """Endow agents with a numerical fitness."""
        try:
            return float(self.property1)
        except TypeError:
            return None

**Comment by thomasmorgan** [comment]
@alecpm Thanks Alec. In response:

**A**:
I have given all the objects a __json__() method, it looks much nicer now

**B**:
good spot. I've rewritten that as 
```(info_in.id not in [t.info_id for t in node.transmissions(direction="incoming", status="received")])```
so it will be much faster now.

**C**:
I made this change too.

Thanks!
