### ISSUE TITLE
rename psiturk table to participants and migrate using csv schemas

### ISSUE THREAD

**Issue by suchow** [suchow/Wallace#259]
@thomasmorgan this is a note to selves that we should talk about this later

**Comment by thomasmorgan** [comment]
@suchow we have effectively done the first part of this right? What does the 2nd part mean?

**Comment by suchow** [comment]
yes, we've done the first part. i'm not sure what the second part meant exactly, and i think this can be closed.

**Comment by thomasmorgan** [comment]
ok
