### ISSUE TITLE
Change the primitive construction of transmissions 

### ISSUE THREAD

**Issue by michaelpacer** [suchow/Wallace#73]
The transmission when created should record the uuid of the vector along which it is sent, as well as the origin and the destination node.

Then it should check to make sure that all of these concur with one another.

This relatedly suggests that we should have a "best coding practices" that discourages the direct assignment of values to the properties of objects in our databases, that way we can assure that everything is consistent with everything else (i.e., so that the origin of the info and the origin of the transmission and the origin node of the vector are all the same).

**Comment by thomasmorgan** [comment]
Transmissions are now defined by a vector and an info, from this they infer their origin node and destination node (and from those their network too). Closing issue.
